# Generated by Django 4.1.2 on 2022-12-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pocdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='country_name',
            field=models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.DO_NOTHING, to='pocdashboard.country'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='detailfacture',
            unique_together={('stock_code', 'invoice_no')},
        ),
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
        migrations.AlterModelTable(
            name='detailfacture',
            table='detailfacture',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='invoice',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
